/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZP9fgAuNNqq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet";

export function Navbar() {
  const navLinks = [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ];

  return (
    <header className=" bg-white px-4">
      <div className="mx-auto flex max-w-[1200px] items-center justify-between py-3 md:px-6 md:py-4">
        <Link
          className="flex items-center gap-2 text-lg font-semibold"
          href="#"
        >
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
          {navLinks.map((navLink) => {
            return (
              <Link
                key={navLink.label}
                className="text-gray-500 transition-colors hover:text-gray-900"
                href={navLink.href}
              >
                {navLink.label}
              </Link>
            );
          })}
        </nav>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="relative" size="icon" variant="outline">
                <ShoppingCartIcon className="h-6 w-6" />
                <Badge className="absolute -right-2 -top-2 h-5 w-5 rounded-full bg-black text-white">
                  3
                </Badge>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-80">
              <DropdownMenuLabel>Shopping Cart</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <div className="max-h-[300px] overflow-y-auto">
                <div className="grid gap-4 p-4">
                  <div className="flex items-center gap-4">
                    <img
                      alt="Product Image"
                      className="rounded-md"
                      height={64}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width={64}
                    />
                    <div className="flex-1">
                      <h4 className="font-medium">Product Name</h4>
                      <p className="text-sm text-gray-500">$19.99</p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <XIcon className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Product Image"
                      className="rounded-md"
                      height={64}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width={64}
                    />
                    <div className="flex-1">
                      <h4 className="font-medium">Another Product</h4>
                      <p className="text-sm text-gray-500">$29.99</p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <XIcon className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Product Image"
                      className="rounded-md"
                      height={64}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width={64}
                    />
                    <div className="flex-1">
                      <h4 className="font-medium">Yet Another Product</h4>
                      <p className="text-sm text-gray-500">$14.99</p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <XIcon className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
              <DropdownMenuSeparator />
              <div className="px-4 py-2">
                <div className="flex items-center justify-between">
                  <span>Total:</span>
                  <span className="font-medium">$64.97</span>
                </div>
                <div className="mt-4 flex gap-2">
                  <Button className="flex-1" variant="outline">
                    View Cart
                  </Button>
                  <Button className="flex-1">Checkout</Button>
                </div>
              </div>
            </DropdownMenuContent>
          </DropdownMenu>
          <Sheet>
            <SheetTrigger asChild>
              <Button className="md:hidden" size="icon" variant="outline">
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="right">
              <nav className="grid gap-4 px-4 py-6">
                {navLinks.map((navLink) => {
                  return (
                    <Link
                      key={navLink.label}
                      className="flex items-center justify-between text-sm font-medium underline-offset-4 hover:underline"
                      href={navLink.href}
                    >
                      {navLink.label}
                      <ChevronRightIcon className="h-5 w-5" />
                    </Link>
                  );
                })}
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </header>
  );
}

function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function ShoppingCartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
